BASE_W = 800
BASE_H = 600

SCREEN_WIDTH = BASE_W
SCREEN_HEIGHT = BASE_H

SCREEN_TITLE = "Фабрика иллюзий"

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FULLSCREEN = False

VISION_MULTIPLIER = 1.0
BRIGHTNESS = 1.0